uploads = []
generated = []

[[outputs]]
id = "leXuiJw5_P0Q6Jkzfoy_-"
uri = "file://medicare-search.tar.gz"
type = "unspecified"
title = "MediCare Search — Project Files"

[[outputs]]
id = "pjoZ1pUxR4JA13nLRI_Bk"
uri = "file://medicare-search-source.tar.gz"
type = "unspecified"
title = "MediCare Search — Updated Source (374 KB)"
