uploads = []
generated = []

[[outputs]]
id = "leXuiJw5_P0Q6Jkzfoy_-"
uri = "file://medicen care-search.tar.gz"
type = "unspecified"
title = "medicen care Search — Project Files"

[[outputs]]
id = "pjoZ1pUxR4JA13nLRI_Bk"
uri = "file://medicen care-search-source.tar.gz"
type = "unspecified"
title = "medicen care Search — Updated Source (374 KB)"
