kind = "web"
previewPath = "/"
title = "medicen care Search"
version = "1.0.0"
id = "artifacts/medicen care-search"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23713

[services.development]
run = "pnpm --filter @workspace/medicen care-search run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/medicen care-search", "run", "build" ]
serve = "static"
publicDir = "artifacts/medicen care-search/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23713"
BASE_PATH = "/"
